# Generated by Django 4.2 on 2023-04-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
